# Site settings
title: 首页
SEOTitle: 徐立辉的博客 | BY Blog
header-img: img/post-bg-desk.jpg
email: mrxuliui@foxmail.com
description: "If you have a better suggestion,Please share out,Let's do better."
keyword: "辉辉的博客, xulihui, 徐立辉, java, javaweb, spring,spring for all"
url: "http://xulihui.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/mrxlh/mrxlh.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     潇凝子潇
zhihu_username:     xulihui
github_username:    mrxlh




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
 Disqus（https://disqus.com/）
 disqus_username: define

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: f16f7ee45c91993ecb69                            #生成的clientID
  clientSecret: 4481f8e63f0b96c8b2bc660b1de945fdd33aef74    #生成的clientSecret
  repo: mrxlh.github.io    #仓库名称
  owner: mrxlh    #github用户名
  admin: mrxuliui@foxmail.com
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-131926961-1'            # Format: UA-xxxxxx-xx
ga_domain: xulihui.com               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "新浪微博",
        href: "https://weibo.com/3194451320/profile"
    },{
        title: "简书·BY",
        href: "http://www.jianshu.com/u/e71990ada2fd"
    }
]
